apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ze5139u21-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:8cd7f45cdfcdacdff3d566e0bda28f5ddca0b24b@sha256:e81667f12ab36e44e35bf95bc07e8363d92cc20fe15189b4c4b6467a0112dce7
          name: container-image
