apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ze5139u21-nodejs
  janus-idp.io/tekton: ze5139u21-nodejs
  backstage.io/kubernetes-id: ze5139u21-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ze5139u21-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
