apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ze5139u21-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ze5139u21-nodejs 
  name: ze5139u21-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ze5139u21-nodejs 
